import type { Metadata } from 'next';
import './globals.css';
import Script from 'next/script';
export const metadata: Metadata = {
    title: 'My New App',
    description: 'Generated by Onlook',
};
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" data-oid="gjbj7ci">
            <body className="" data-oid="u5yexdv">
                {children}

                <Script src="/builtwith.js" strategy="afterInteractive" data-oid="nms5j0:" />
            </body>
        </html>
    );
}
